### ISSUE TITLE
TOML Inline Tables?

### ISSUE THREAD

**Issue by dsully** [PyO3/pyproject-toml-rs#29]
Is it possible to serialize to TOML with inline tables?

Currently serialization will emit a section such as:

```toml
[tool.uv.sources.myapp]
path = "./src"
```

Where I'd prefer:

```toml
[tool.uv.sources]
myapp = { path = "./src" }
```

I've tried with both `toml::to_string()` and `toml::to_string_pretty()`

Thanks!
